dynamixel_arm:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    arm_controller:
       type: "position_controllers/JointTrajectoryController"
       joints:
           - joint1
           - joint2
           - joint3
           - joint4
           - joint5
               
       # gains: 
           # joint1: {p: 700, i: 0.01, d: 25, i_clamp: 1}
           # joint2: {p: 10000, i: 100, d: 100, i_clamp: 1}
           # joint3: {p: 4500, i: 35, d: 1, i_clamp: 1}
           # joint4: {p: 5500, i: 60, d: 2, i_clamp: 1}
           # joint5: {p: 1000, i: 30, d: 0.01, i_clamp: 1}
           # joint6: {p: 900, i: 0.1, d: 0.01, i_clamp: 1}
